jwt:
  secret: radhouenPOC
server:
  port: 8081

spring:
  mail:
    protocol: smtp
    host: smtp.gmail.com
    port: 587
    username: raniahamdeni28.11.00@gmail.com
    password: snnfcopwsetfwkqr
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
      show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/smartbox_database
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  logging:
    level:
      org.hibernate: debug
      com.zaxxer.hikari: debug
